### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by surjitkumar25** [raykolbe/DOMPDFModule#38] opened 2016-03-15 10:46 UTC
this works fine with (0.6.1) of dompdf/dompdf but after updating composer http://prntscr.com/afhlct

**Comment by marciodojr** [comment] 2016-03-15 14:16
Duplicate of #37

**Comment by raykolbe** [comment] 2016-10-30 14:17
Closing due to duplicate issue #37.

**Closed by raykolbe** 2016-10-30 14:17 UTC
